added student endpoints
TheLocagus/MegaK-Team20-Backend pull request #25
Opened 2022-08-01 16:55 UTC by arakeee

2022-08-01 19:02 UTC, Adam-DevPL requested changes
There is a major issue with endpoints POST and PATCH.
In POST we should create new Student and moreover now it looks like and update
In PATCH we update the Student, so this method createStudent could work, ut with small changes.

2022-08-01 19:02 UTC, Adam-DevPL commented on src/student/student.controller.ts
> +    @Post('/register/:id')
endpoint should be /:id not register/:id

2022-08-01 19:02 UTC, Adam-DevPL commented on src/student/student.service.ts
> +    }
This should be done on StudentImport not Student. And we return id of StudentImport

2022-08-01 19:02 UTC, Adam-DevPL commented on src/student/student.service.ts
> +                id: student.id,
id should be generated from uuid

2022-08-01 19:02 UTC, Adam-DevPL commented on src/student/student.service.ts
> +                password: createStudentDto.password,
password should be hashed --> there is special funtion made to o it

2022-08-01 19:02 UTC, Adam-DevPL commented on src/student/student.service.ts
> +    }
there should set up a field studentImport = id

2022-08-01 19:02 UTC, Adam-DevPL commented on src/student/student.controller.ts
> +}
Should be different method for update DB, not createStudent. 
createStudent is for creating new Student and when we use the same method for patch it will overwrite some fields, that shouldn't be overwritten, like currentTokenId or password. 
Of course it can be done in one method, but it must be  well thought

2022-08-01 19:02 UTC, Adam-DevPL commented on src/student/student.service.ts
> +            .update(Student)
it's not update when you create new Student
at the beginning there is no Student in the database, so update won't work

2022-08-03 18:40 UTC, PioR94 approved these changes

2022-08-04 19:26 UTC, closed without merging